name:                penstrokes
version:             0.1.0.0
github:              "jmdurr/penstrokes"
license:             BSD3
author:              "Jonathan Durr"
maintainer:          "jmdurr@gmail.com"
copyright:           "2019 Jonathan Durr All Rights Reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jmdurr/penstrokes#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- freetype2
- exceptions
- text
- vector
- array
- containers

library:
  source-dirs: src

tests:
  penstrokes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - penstrokes
